# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.profile:
        class: TL\UserBundle\Form\ProfileEditType
        tags:
            - { name: form.type, alias: app_user_profile_edit }